<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/TraceableValueResolver.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';

return $this->privates['debug.argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver(new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(array('App\\Controller\\DefaultController::index' => function () {
    return ($this->privates['.service_locator.XMePXeM'] ?? $this->load('get_ServiceLocator_XMePXeMService.php'));
}, 'App\\Controller\\LoginController::index' => function () {
    return ($this->privates['.service_locator.XMePXeM'] ?? $this->load('get_ServiceLocator_XMePXeMService.php'));
}, 'App\\Controller\\LoginController::logout' => function () {
    return ($this->privates['.service_locator.XMePXeM'] ?? $this->load('get_ServiceLocator_XMePXeMService.php'));
}, 'App\\Controller\\QuizzController::index' => function () {
    return ($this->privates['.service_locator.XMePXeM'] ?? $this->load('get_ServiceLocator_XMePXeMService.php'));
}, 'App\\Controller\\RegisterController::index' => function () {
    return ($this->privates['.service_locator.XMePXeM'] ?? $this->load('get_ServiceLocator_XMePXeMService.php'));
}, 'App\\Controller\\UserController::delete' => function () {
    return ($this->privates['.service_locator.iuuVGtK'] ?? $this->load('get_ServiceLocator_IuuVGtKService.php'));
}, 'App\\Controller\\UserController::edit' => function () {
    return ($this->privates['.service_locator..Fqifov'] ?? $this->load('get_ServiceLocator__FqifovService.php'));
}, 'App\\Controller\\UserController::index' => function () {
    return ($this->privates['.service_locator.79NGwOx'] ?? $this->load('get_ServiceLocator_79NGwOxService.php'));
}, 'App\\Controller\\UserController::new' => function () {
    return ($this->privates['.service_locator.XMePXeM'] ?? $this->load('get_ServiceLocator_XMePXeMService.php'));
}, 'App\\Controller\\UserController::show' => function () {
    return ($this->privates['.service_locator..Fqifov'] ?? $this->load('get_ServiceLocator__FqifovService.php'));
}, 'App\\Controller\\DefaultController:index' => function () {
    return ($this->privates['.service_locator.XMePXeM'] ?? $this->load('get_ServiceLocator_XMePXeMService.php'));
}, 'App\\Controller\\LoginController:index' => function () {
    return ($this->privates['.service_locator.XMePXeM'] ?? $this->load('get_ServiceLocator_XMePXeMService.php'));
}, 'App\\Controller\\LoginController:logout' => function () {
    return ($this->privates['.service_locator.XMePXeM'] ?? $this->load('get_ServiceLocator_XMePXeMService.php'));
}, 'App\\Controller\\QuizzController:index' => function () {
    return ($this->privates['.service_locator.XMePXeM'] ?? $this->load('get_ServiceLocator_XMePXeMService.php'));
}, 'App\\Controller\\RegisterController:index' => function () {
    return ($this->privates['.service_locator.XMePXeM'] ?? $this->load('get_ServiceLocator_XMePXeMService.php'));
}, 'App\\Controller\\UserController:delete' => function () {
    return ($this->privates['.service_locator.iuuVGtK'] ?? $this->load('get_ServiceLocator_IuuVGtKService.php'));
}, 'App\\Controller\\UserController:edit' => function () {
    return ($this->privates['.service_locator..Fqifov'] ?? $this->load('get_ServiceLocator__FqifovService.php'));
}, 'App\\Controller\\UserController:index' => function () {
    return ($this->privates['.service_locator.79NGwOx'] ?? $this->load('get_ServiceLocator_79NGwOxService.php'));
}, 'App\\Controller\\UserController:new' => function () {
    return ($this->privates['.service_locator.XMePXeM'] ?? $this->load('get_ServiceLocator_XMePXeMService.php'));
}, 'App\\Controller\\UserController:show' => function () {
    return ($this->privates['.service_locator..Fqifov'] ?? $this->load('get_ServiceLocator__FqifovService.php'));
}))), ($this->privates['debug.stopwatch'] ?? $this->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true)));
