index:
    path: /
    controller: App\Controller\DefaultController::index
register:
    path: /register
    controller: App\Controller\RegisterController::index
logout:
    path: /logout
    controller: App\Controller\LoginController::logout
quizz:
    path: /quizz
    controller: App\Controller\QuizzController::index