<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerN5YW8h8\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerN5YW8h8/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerN5YW8h8.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerN5YW8h8\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerN5YW8h8\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'N5YW8h8',
    'container.build_id' => 'b41433c8',
    'container.build_time' => 1544280156,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerN5YW8h8');
